# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:36:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Organization(BaseModel):
    organizationId: Optional[str] = Field(
        None, description='Required. ID of the organization.'
    )
    organizationName: Optional[str] = Field(
        None,
        description='Optional. A human-readable name of the organization, to help recognize the organization.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class CustomApp(BaseModel):
    languageCode: Optional[str] = Field(
        None, description='Default listing language in BCP 47 format.'
    )
    organizations: Optional[List[Organization]] = Field(
        None,
        description='Organizations to which the custom app should be made available. If the request contains any organizations, then the app will be restricted to only these organizations. To support the organization linked to the developer account, the organization ID should be provided explicitly together with other organizations. If no organizations are provided, then the app is only available to the organization linked to the developer account.',
    )
    packageName: Optional[str] = Field(
        None,
        description='Output only. Package name of the created Android app. Only present in the API response.',
    )
    title: Optional[str] = Field(None, description='Title for the Android app.')
